# Generated by Django 3.1.6 on 2021-03-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ask_expert',
        ),
        migrations.DeleteModel(
            name='crop_master',
        ),
        migrations.DeleteModel(
            name='crop_master_details',
        ),
        migrations.DeleteModel(
            name='cultivation_master',
        ),
        migrations.DeleteModel(
            name='disease_info',
        ),
        migrations.DeleteModel(
            name='expert_details',
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
        migrations.DeleteModel(
            name='fertilizer_master',
        ),
        migrations.DeleteModel(
            name='pesticides_info',
        ),
    ]
