# Generated by Django 3.1.6 on 2021-03-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210303_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='kcno',
        ),
    ]
