# Generated by Django 4.0 on 2026-02-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_details_kcno'),
    ]

    operations = [
        migrations.CreateModel(
            name='creator_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('pic', models.CharField(max_length=300)),
                ('dob', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('test_url', models.CharField(max_length=100)),
                ('descp', models.CharField(max_length=100)),
                ('pic1', models.CharField(max_length=100)),
                ('pic2', models.CharField(max_length=100)),
                ('pic3', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=100)),
                ('tm', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('portfolio_id', models.IntegerField()),
                ('rating', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=500)),
                ('dt', models.CharField(max_length=100)),
                ('tm', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='purchase_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('dt', models.CharField(max_length=100)),
                ('tm', models.CharField(max_length=100)),
                ('amt', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='search_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('keyword', models.CharField(max_length=200)),
                ('dt', models.CharField(max_length=100)),
                ('tm', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='pin',
        ),
        migrations.AddField(
            model_name='user_details',
            name='status',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_details',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.CharField(max_length=250),
        ),
    ]
