# Generated by Django 4.0 on 2026-02-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_creator_details_portfolio_details_portfolio_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_details',
            name='filepath',
            field=models.CharField(default='nofile', max_length=300),
            preserve_default=False,
        ),
    ]
