# Generated by Django 4.0 on 2026-02-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_portfolio_details_filepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('arch_id', models.IntegerField()),
                ('requirments', models.CharField(max_length=250)),
                ('filepath', models.CharField(max_length=250)),
                ('remark', models.CharField(max_length=250)),
                ('amt', models.CharField(max_length=250)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
    ]
